var searchData=
[
  ['libsqsh_0',['libsqsh',['../md_libsqsh_2README.html',1,'libsqsh'],['../index.html#autotoc_md6',1,'libsqsh']]],
  ['libsqsh_20actions_20workflows_20ci_20yaml_20badge_20svg_20alt_20ci_20a_20a_20href_20https_3a_20codecov_20io_20github_20gottox_20sqsh_20tools_20img_20src_20https_3a_20codecov_20io_20github_20gottox_20sqsh_20tools_20graph_20badge_20svg_20token_20am5copdmh0_20alt_20codecov_20a_20a_20href_20https_3a_20sonarcloud_20io_20summary_20new_5fcode_20id_20gottox_5flibsqsh_20img_20src_20https_3a_20sonarcloud_20io_20api_20project_5fbadges_20measure_20project_20gottox_5flibsqsh_20metric_20alert_5fstatus_20alt_20quality_20gate_20status_20a_20a_20href_20https_3a_20opensource_20org_20licenses_20bsd_202_20clause_20img_20src_20https_3a_20img_20shields_20io_20badge_20license_20bsd_5f2_20clause_20orange_20svg_20alt_20license_20a_1',['sqsh-tools &lt;a href=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml&quot; &gt;&lt;img src=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://codecov.io/github/Gottox/sqsh-tools&quot; &gt;&lt;img src=&quot;https://codecov.io/github/Gottox/sqsh-tools/graph/badge.svg?token=AM5COPDMH0&quot; alt=&quot;codecov&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://sonarcloud.io/summary/new_code?id=Gottox_libsqsh&quot; &gt;&lt;img src=&quot;https://sonarcloud.io/api/project_badges/measure?project=Gottox_libsqsh&amp;metric=alert_status&quot; alt=&quot;Quality Gate Status&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://opensource.org/licenses/BSD-2-Clause&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/License-BSD_2--Clause-orange.svg&quot; alt=&quot;License&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['libsqsh_20actions_20workflows_20ci_20yaml_20img_20src_20https_3a_20github_20com_20gottox_20libsqsh_20actions_20workflows_20ci_20yaml_20badge_20svg_20alt_20ci_20a_20a_20href_20https_3a_20codecov_20io_20github_20gottox_20sqsh_20tools_20img_20src_20https_3a_20codecov_20io_20github_20gottox_20sqsh_20tools_20graph_20badge_20svg_20token_20am5copdmh0_20alt_20codecov_20a_20a_20href_20https_3a_20sonarcloud_20io_20summary_20new_5fcode_20id_20gottox_5flibsqsh_20img_20src_20https_3a_20sonarcloud_20io_20api_20project_5fbadges_20measure_20project_20gottox_5flibsqsh_20metric_20alert_5fstatus_20alt_20quality_20gate_20status_20a_20a_20href_20https_3a_20opensource_20org_20licenses_20bsd_202_20clause_20img_20src_20https_3a_20img_20shields_20io_20badge_20license_20bsd_5f2_20clause_20orange_20svg_20alt_20license_20a_2',['sqsh-tools &lt;a href=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml&quot; &gt;&lt;img src=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://codecov.io/github/Gottox/sqsh-tools&quot; &gt;&lt;img src=&quot;https://codecov.io/github/Gottox/sqsh-tools/graph/badge.svg?token=AM5COPDMH0&quot; alt=&quot;codecov&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://sonarcloud.io/summary/new_code?id=Gottox_libsqsh&quot; &gt;&lt;img src=&quot;https://sonarcloud.io/api/project_badges/measure?project=Gottox_libsqsh&amp;metric=alert_status&quot; alt=&quot;Quality Gate Status&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://opensource.org/licenses/BSD-2-Clause&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/License-BSD_2--Clause-orange.svg&quot; alt=&quot;License&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['license_20a_3',['sqsh-tools &lt;a href=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml&quot; &gt;&lt;img src=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://codecov.io/github/Gottox/sqsh-tools&quot; &gt;&lt;img src=&quot;https://codecov.io/github/Gottox/sqsh-tools/graph/badge.svg?token=AM5COPDMH0&quot; alt=&quot;codecov&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://sonarcloud.io/summary/new_code?id=Gottox_libsqsh&quot; &gt;&lt;img src=&quot;https://sonarcloud.io/api/project_badges/measure?project=Gottox_libsqsh&amp;metric=alert_status&quot; alt=&quot;Quality Gate Status&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://opensource.org/licenses/BSD-2-Clause&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/License-BSD_2--Clause-orange.svg&quot; alt=&quot;License&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['license_20bsd_5f2_20clause_20orange_20svg_20alt_20license_20a_4',['sqsh-tools &lt;a href=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml&quot; &gt;&lt;img src=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://codecov.io/github/Gottox/sqsh-tools&quot; &gt;&lt;img src=&quot;https://codecov.io/github/Gottox/sqsh-tools/graph/badge.svg?token=AM5COPDMH0&quot; alt=&quot;codecov&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://sonarcloud.io/summary/new_code?id=Gottox_libsqsh&quot; &gt;&lt;img src=&quot;https://sonarcloud.io/api/project_badges/measure?project=Gottox_libsqsh&amp;metric=alert_status&quot; alt=&quot;Quality Gate Status&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://opensource.org/licenses/BSD-2-Clause&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/License-BSD_2--Clause-orange.svg&quot; alt=&quot;License&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['licenses_20bsd_202_20clause_20img_20src_20https_3a_20img_20shields_20io_20badge_20license_20bsd_5f2_20clause_20orange_20svg_20alt_20license_20a_5',['sqsh-tools &lt;a href=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml&quot; &gt;&lt;img src=&quot;https://github.com/Gottox/libsqsh/actions/workflows/ci.yaml/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://codecov.io/github/Gottox/sqsh-tools&quot; &gt;&lt;img src=&quot;https://codecov.io/github/Gottox/sqsh-tools/graph/badge.svg?token=AM5COPDMH0&quot; alt=&quot;codecov&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://sonarcloud.io/summary/new_code?id=Gottox_libsqsh&quot; &gt;&lt;img src=&quot;https://sonarcloud.io/api/project_badges/measure?project=Gottox_libsqsh&amp;metric=alert_status&quot; alt=&quot;Quality Gate Status&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://opensource.org/licenses/BSD-2-Clause&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/License-BSD_2--Clause-orange.svg&quot; alt=&quot;License&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['list_6',['Deprecated List',['../deprecated.html',1,'']]],
  ['list_5fdir_2ec_7',['list_dir.c',['../list__dir_8c.html',1,'']]],
  ['list_5fdir_5fll_2ec_8',['list_dir_ll.c',['../list__dir__ll_8c.html',1,'']]],
  ['list_5fxattrs_2ec_9',['list_xattrs.c',['../list__xattrs_8c.html',1,'']]],
  ['list_5fxattrs_5fll_2ec_10',['list_xattrs_ll.c',['../list__xattrs__ll_8c.html',1,'']]],
  ['lzo2_11',['LZO2',['../index.html#autotoc_md7',1,'']]]
];
