# https://github.com/Gottox/mk
configure:
  - -Dwerror=true
  - -Ddefault_library=static
  - -Dcurl=enabled
  - -Dzlib=enabled
  - -Dlz4=enabled
  - -Dlzma=enabled
  - -Dzstd=enabled
  - -Dfuse=enabled
  - -Dfuse-old=enabled

mode:
  default:
    configure:
      - -Db_lundef=false
      - -Dtest=true
      - -Ddoc=internal
      - -Dexamples=true
      - -Db_coverage=true
      - -Db_sanitize=address,undefined
    default:
      - test
  bench:
    configure:
      - --optimization=3
      - -Ddebug=true
      - -Dtest=false
      - -Dexamples=false
      - -Dfuzzer=false
      - -Ddoc=false
      - -Db_coverage=false
      - -Db_sanitize=none
      - -Db_lto=true
  fuzz:
    configure:
      - -Dfuzzer=true
      - -Dfuzzer_timeout=300
  extended:
    configure:
      - -Db_lundef=false
      - -Dtest=extended
      - -Ddoc=internal
      - -Dexamples=true
      - -Db_sanitize=address,undefined
    default:
      - test
  clang:
    env:
      CC: clang
